---
title: JPE Replication Report
date: today
number-sections: true
format:
  html: default
---

# Paper Identification

|  |   |
| ---  |  -------|
| ID  |  {{< var paper_id >}} |
| Author  | Vincenzo Lardo |
| Title  |  “The Effect of Age at Graduation on Family Formation: Evidence from the Bologna Process” |
| Iteration |  Round 1 |


Some useful information up front:

- [JPE Data and Code Availability Policy](https://www.journals.uchicago.edu/journals/jpe/datapolicy)
- [Step by step guidance from Data Editor for Authors](https://jpedataeditor.github.io/) 
- [Template README](https://social-science-data-editors.github.io/template_README/)


# Summary

In assessing compliance with our [Data and Code Availability Policy](https://www.journals.uchicago.edu/journals/jpe/datapolicy), our reproducibility team has identified the following issues, which we ask you to address:

1. Data Editor's first point.
2. Data Editor's second point.

# General

- [ ] Data Availability and Provenance Statements
  - [x] Statement about Rights - Part 1: Right to use the data (e.g. *did the authors lawfully obtain the data*)
  - [ ] Statement about Rights - Part 2: Right to publish the data (e.g. *are human subjects involved and did permission been granted to publish their data?*)
  - [ ] License for Data (optional, but recommended)
  - [ ] Details on each Data Source
- [ ] Dataset list
- [x] Computational requirements
  - [x] Software Requirements
  - [ ] Controlled Randomness (as necessary)
  - [ ] Memory, Runtime, and Storage Requirements
- [x] Description of programs/code
  - [ ] License for Code (Optional, but recommended) 
- [x] List of tables and programs
- [ ] References (Optional, but recommended) 


# High-level Description of Research Project

*This research project...*

- [x] uses observational data.
- [ ] uses *confidential* observational data.
- [ ] uses data generated via experiment or trial by the authors (in field or lab).
  - [ ] For lab experiments: The code to implement the experimental protocol (z-Tree, o-Tree etc) is included in the package.
  - [ ] A PDF copy of IRB approval is contained in the package.
  - [ ] A PDF document outlining the design of the experiment, including information on the selection and eligibility of participants is included.
  - [ ] A PDF copy of the instructions given to participants in both original language and an English translation is included.
- [ ] uses data generated via survey by the authors (in field or online)
  - [ ] The programs used to administer the survey (e.g. qualtrics survey file) are included.
  - [ ] A PDF copy of IRB approval is contained in the package.
  - [ ] A PDF of the original questionaire(s) and information on the selection and eligibility of participants is included.
- [ ] is a simulation study: the data are generated by an algorithm.
- [ ] is a numerical illustration: no data are used but code is used to produce illustrative output (tables, figures)


# Data description

## Data Sources

| file/name            | public | private | DOI/URL | Access described| cited readme | cited paper |
| ----                 | ---    | ---     | ---     | ---             | ----         | ----        | 
| Data/raw_data/LFS_2014/RCFL_Microdati_Anno_2014_Primo_trimestre.txt | yes    | no      | no      | no              | no           | N/A         |
| same for all quarters 2014-2020         |     |       |     |               |            |          |


# Requirements 

- [x] README is in TXT, MD, or PDF format
- [x] README is accessible at the root of the package (not inside a folder)
- [ ] Title conforms to guidance (starts with "Data and Code for: Title of Paper" or "Code for: Title of Paper", is properly capitalized)
- [ ] Authors (with affiliations) are listed in the same order as on the paper


> {REQUIRED} Please ensure that a ASCII (txt), Markdown (md), or PDF version of the README are available in the data and code deposit.

> {REQUIRED} Please review the title of the deposit as per our guidelines.

> {REQUIRED} Please review authors and affiliations on the deposit. In general, they are the same, and in the same order, as for the manuscript; however, authors can deviate from that order.


## Stated Requirements

- [ ] No requirements specified
- [x] Software Requirements specified as follows:
  - Software 1 Stata 18
  - Software 2
- [ ] Computational Requirements specified as follows:
  - Cluster size, etc.
- [x] Time Requirements specified as follows:
  - Length of necessary computation (hours, weeks, etc.)

- [ ] Requirements are complete.

For missing requirements, see the list of required changes in @sec-findings

# Analyzing Data and Code Files

## Code description

- [x] The replication package contains a "main" or "master" file(s) which calls all other auxiliary programs.

#The file is called run.do


## Computing Environment of the Replicator

MAcBook Air M2, 2022, MacOS Tahoe 26.2, 8 GB of memory, (M2 Processor)

- Stata/MP 19.0


# Replication

- Downloaded code and data from email.
- I commented out the path and added my own
- Commited code to git repo
- Ran code as per README, but the cd did not work as suggested in read me, so I commented them out and just added my path
- Code ran to completion

# Findings {#sec-findings}

The files run and the table replicates. 

## Missing Requirements

- [ ] Computational Requirements specified as follows:
  - Cluster size, disk size, memory size, etc.

> [REQUIRED] Please amend README to contain complete requirements. 

## Data Preparation Code

- Program `ode/configuration/configuration.do` ran without error, output expected data
- Program `code/import_append/01_import_and_append_lfs.do` ran without error, output expected data
- Program `code/processed/02_build_analysis_dataset.do` ran without error, output expected data


## Tables and Figures

| Figure/Table #      | Program                                          | Line Number | Reproduced? |
|---------------------|--------------------------------------------------|-------------|-------------|
| Summary Statistics  | do "code//descriptives/03_descriptives_stats.do" | 38          | yes         |


- Table Summary statistics reproduces


## In-Text Numbers

There is no paper version of this project, only one table. 

## Other Issues

No other issues 

# Classification

- [x] full reproduction
- [ ] full reproduction with minor issues
- [ ] partial reproduction (see above)
- [ ] not able to reproduce most or all of the results (reasons see above)

## Reason for incomplete reproducibility

- [x] None.
- [ ] `Discrepancy in output` (either figures or numbers in tables or text differ)
- [ ] `Bugs in code` that were fixable by the replicator (but should be fixed in the final deposit)
- [ ] `Code missing`, in particular if it prevented the replicator from completing the reproducibility check
  - [ ] `Data preparation code missing` should be checked if the code missing seems to be data preparation code
- [ ] `Code not functional` is more severe than a simple bug: it prevented the replicator from completing the reproducibility check
- [ ] `Software not available to replicator` may happen for a variety of reasons, but in particular (a) when the software is commercial, and the replicator does not have access to a licensed copy, or (b) the software is open-source, but a specific version required to conduct the reproducibility check is not available.
- [ ] `Insufficient time available to replicator` is applicable when (a) running the code would take weeks or more (b) running the code might take less time if sufficient compute resources were to be brought to bear, but no such resources can be accessed in a timely fashion (c) the replication package is very complex, and following all (manual and scripted) steps would take too long.
- [ ] `Data missing` is marked when data *should* be available, but was erroneously not provided, or is not accessible via the procedures described in the replication package
- [ ] `Data not available` is marked when data requires additional access steps, for instance purchase or application procedure. 
- [ ] `Missing README` is marked if there is no README to guide the replicator, or the README is not in compliance with JPE requirements


{{< include generated/report-pii.md >}}
